//
//  HomeViewController.swift
//  project-saarah
//
//  Created by Bruno Rocha on 29/09/19.
//  Copyright (c) 2019 Bruno Rocha. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeDisplayLogic: class {
	func displaySomething(viewModel: Home.Something.ViewModel)
    func displayHomeNotifications (viewModel: Home.FetchHomeNotifications.ViewModel)
}

class HomeViewController: SaarahViewController, HomeDisplayLogic {
	// MARK: Property
	var interactor: HomeBusinessLogic?
	var router: (NSObjectProtocol & HomeRoutingLogic & HomeDataPassing)?

    private var homeView = HomeView()
    private var homeMenuOptions = HomeMenuOption.allCases
    private var displayedHomeNotifications = [Home.FetchHomeNotifications.ViewModel.DisplayedHomeNotification]()

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder: NSCoder) {
        super.init(coder: coder)
        setup()
    }

	// MARK: View lifecycle
	override func viewDidLoad() {
		super.viewDidLoad()
        defaultViewControllerConfiguration()
		requestHomeNotifications()
	}

	// MARK: Setup
	private func setup() {
		let viewController = self
		let interactor = HomeInteractor()
		let presenter = HomePresenter()
		let router = HomeRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
		router.dataStore = interactor
	}

    func defaultViewControllerConfiguration () {
        title = "Restaurante"
        view = homeView
        homeView.tableView.delegate = self
        homeView.tableView.dataSource = self
    }

	// MARK: Do something
	func doSomething() {
		let request = Home.Something.Request()
		interactor?.doSomething(request: request)
	}
    
    func requestHomeNotifications () {
        let request = Home.FetchHomeNotifications.Request()
        interactor?.fetchHomeNotifications(request: request)
    }

	func displaySomething(viewModel: Home.Something.ViewModel) {
		//nameTextField.text = viewModel.name
	}

    func displayHomeNotifications (viewModel: Home.FetchHomeNotifications.ViewModel) {
        displayedHomeNotifications = viewModel.displayedHomeNotifications
        homeView.tableView.reloadData()
    }
}

extension HomeViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        switch section {
        case 0:
            return 1
        case 1:
            return displayedHomeNotifications.count
        default:
            return 0
        }
    }

    func numberOfSections(in tableView: UITableView) -> Int {
        return 2
    }

    func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
        switch section {
        case 0:
            return EmptySectionHeaderView()
        case 1:
            let headerView = DefaultSectionHeaderView()
            headerView.titleLabel.text = "NOTIFICAÇÕES"
            headerView.rightButton.setTitle("VER TODAS", for: .normal)
            return headerView
        default:
            return nil
        }
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        switch indexPath.section {
        case 0:
            let cell = HomeMenuTableViewCell()
            cell.homeMenuOptions = homeMenuOptions
            cell.delegate = self
            return cell
        default:
            let cell = DefaultCellTableViewCell()
            let index = indexPath.row
            cell.label.text = "\(displayedHomeNotifications[index].emoji) \(displayedHomeNotifications[index].message)"
            cell.roundCellIfNeeded(index: indexPath.row, numberOfCells: displayedHomeNotifications.count)
            return cell
        }
    }
}

extension HomeViewController: HomeMenuDelegate {
    func didSelectHomeMenuOption(_ option: HomeMenuOption) {
        let nextViewController = option.viewController
        router?.navigateTo(source: self, destination: nextViewController)
    }
}
