//
//  HomeRouter.swift
//  project-saarah
//
//  Created by Bruno Rocha on 29/09/19.
//  Copyright (c) 2019 Bruno Rocha. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
	func navigateTo (source: HomeViewController, destination: UIViewController)
}

protocol HomeDataPassing {
	var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing {
	weak var viewController: HomeViewController?
	var dataStore: HomeDataStore?
    
    func navigateTo (source: HomeViewController, destination: UIViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }

// MARK: Passing data
//	func passDataToSomewhere(source: HomeDataStore, destination: inout SomewhereDataStore) {
//		destination.name = source.name
//	}
}
