//
//  HomeWorker.swift
//  project-saarah
//
//  Created by Bruno Rocha on 29/09/19.
//  Copyright (c) 2019 Bruno Rocha. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeWorker {
	func doSomeWork() {
	}
}

protocol HomeNotificationStoreProtocol {
    func fetchNotifications (completionHandler: @escaping ([HomeNotification]) -> Void)
}

class HomeNotificationsWorker {
    var notificationStore: HomeNotificationStoreProtocol

    init(notificationStore: HomeNotificationStoreProtocol) {
        self.notificationStore = notificationStore
    }

    func fetchNotifications (completionHandler: @escaping ([HomeNotification]) -> Void) {
        notificationStore.fetchNotifications { homeNotifications in
            DispatchQueue.main.async {
                completionHandler(homeNotifications)
            }
        }
    }

    func createNotification (_ notification: HomeNotification, completionHandler: @escaping (HomeNotification?) -> Void) {

    }
}
