//
//  HomeViewController.swift
//  project-saarah
//
//  Created by Bruno Rocha on 29/09/19.
//  Copyright (c) 2019 Bruno Rocha. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeDisplayLogic: class {
	func displaySomething(viewModel: Home.Something.ViewModel)
}

class HomeViewController: SaarahViewController, HomeDisplayLogic {
	// MARK: Property
	var interactor: HomeBusinessLogic?
	var router: (NSObjectProtocol & HomeRoutingLogic & HomeDataPassing)?
    var homeView = HomeView()

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder: NSCoder) {
        super.init(coder: coder)
        setup()
    }

	// MARK: View lifecycle
	override func viewDidLoad() {
		super.viewDidLoad()
        defaultViewControllerConfiguration()
		doSomething()
	}

	// MARK: Setup
	private func setup() {
		let viewController = self
		let interactor = HomeInteractor()
		let presenter = HomePresenter()
		let router = HomeRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
		router.dataStore = interactor
	}

    func defaultViewControllerConfiguration () {
        title = "Restaurante"
        view = homeView
        homeView.delegate = self
    }

	// MARK: Do something
	func doSomething() {
		let request = Home.Something.Request()
		interactor?.doSomething(request: request)
	}

	func displaySomething(viewModel: Home.Something.ViewModel) {
		//nameTextField.text = viewModel.name
	}
}

extension HomeViewController: HomeViewDelegate {
    func didRequestNavigationTo(nextViewController: UIViewController) {
        self.router?.navigateTo(source: self, destination: nextViewController)
    }
}
