//
//  HomeView.swift
//  project-saarah
//
//  Created by Bruno Rocha on 29/09/19.
//  Copyright (c) 2019 Bruno Rocha. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct SaarahTableViewSection {
    var headerView: UIView
    var cells: [UITableViewCell]
}

class HomeView: UIView {
    var tableView = SaarahTableView()

    var tableViewSections = [SaarahTableViewSection]()
    private var homeMenuSection: Int!
    private var notificationsSection: Int!

	init() {
        super.init(frame: .zero)

        backgroundColor = AppStyleGuide.Colors.background.uiColor
		instantiateViews()
		buildViewsHierarchy()
		setupConstraints()
	}

	required init?(coder aDecoder: NSCoder) {
		fatalError("init(coder:) has not been implemented")
	}

	func instantiateViews() {}

	func buildViewsHierarchy() {
        addSubview(tableView)
	}

	func setupConstraints() {
        NSLayoutConstraint.activate([
            tableView.topAnchor.constraint(equalTo: topAnchor),
            tableView.leadingAnchor.constraint(equalTo: safeAreaLayoutGuide.leadingAnchor),
            tableView.trailingAnchor.constraint(equalTo: safeAreaLayoutGuide.trailingAnchor),
            tableView.bottomAnchor.constraint(equalTo: bottomAnchor)
        ])
	}

    func buildHomeMenuSection (homeMenuCollectionDelegate delegate: UICollectionViewDelegate, homeMenuCollectionDataSource dataSource: UICollectionViewDataSource) {
        let homeMenuTableViewCell = HomeMenuTableViewCell()
        homeMenuTableViewCell.homeMenuCollectionView.delegate = delegate
        homeMenuTableViewCell.homeMenuCollectionView.dataSource = dataSource
        homeMenuSection = tableViewSections.count

        let section = SaarahTableViewSection(headerView: EmptySectionHeaderView(), cells: [homeMenuTableViewCell])
        tableViewSections.append(section)
    }

    func buildNotificationsSection () {
        let secondSectionHeaderView = DefaultSectionHeaderView()
        secondSectionHeaderView.titleLabel.text = "NOTIFICAÇÕES"
        secondSectionHeaderView.rightButton.setTitle("VER TODAS", for: .normal)
        let section = SaarahTableViewSection(headerView: secondSectionHeaderView, cells: [])
        notificationsSection = tableViewSections.count
        tableViewSections.append(section)
    }

    func addNotificationCell (with displayedHomeNotification: Home.FetchHomeNotifications.ViewModel.DisplayedHomeNotification) {
        let cell = HomeNotificationTableViewCell()
        cell.messageLabel.text = displayedHomeNotification.message
        cell.emojiLabel.text = displayedHomeNotification.emoji
        cell.type = displayedHomeNotification.type
        tableViewSections[notificationsSection].cells.append(cell)
    }
}
